config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: { confirmations: 'confirmations' }
  root 'books#index'
  get '/books/indexadmin', to: 'books#indexadmin', as: 'books_indexadmin'
  get '/books/showadmin/:id', to: 'books#showadmin', as: 'books_showadmin'
  get '/profiles/select', to: 'profiles#select', as: 'profiles_select'
  get '/profiles/cambiar', to: 'profiles#cambiar', as: 'profiles_cambiar'
  get '/profiles/selectplan', to: 'profiles#selectplan', as: 'profiles_selectplan'
  get '/profiles/cambiarplan1', to: 'profiles#cambiarplan1', as: 'profiles_cambiarplan1'
  get '/profiles/cambiarplan2', to: 'profiles#cambiarplan2', as: 'profiles_cambiarplan2'
  get '/profiles/cambiartarjeta', to: 'profiles#cambiartarjeta', as: 'profiles_cambiartarjeta'
  resources :notices
  resources :favorites
  resources :markers
  resources :seelaters
  resources :books
  resources :profiles
  resources :welcome
  resources :books do
  	resources :capitulos
  end
  resources :commentaries
  resources :votes
  resources :authors
  get '/books/:book_id/capitulos/:id/borrar', to: 'capitulos#borrar', as: 'borrar_book_capitulo'

end

app/models/author.rb
class Author < ApplicationRecord
  has_and_belongs_to_many :books
end

app/models/authors_book.rb
class AuthorsBook < ApplicationRecord
  belongs_to :book
  belongs_to :author
end

app/models/book.rb
class Book < ApplicationRecord

   validate :indate_bigger_tan_outdate
   has_and_belongs_to_many :authors
   has_one_attached :image
   has_many :favorites
   has_many :seelaters
   has_many :markers
   belongs_to :genre
   belongs_to :category
   validates_uniqueness_of :isbn, :on => :create
   validates_uniqueness_of :isbn, :on => :update

   has_many :capitulos
   has_many :commentaries



  def indate_bigger_tan_outdate
    if indate > outdate
      errors.add(:indate, "La fecha de lanzamiento no puede ser mas lejana que la de vencimiento ")
    end
  end

end

app/models/capitulo.rb
class Capitulo < ApplicationRecord
	belongs_to :book
	validate :expiration_date_cannot_be_in_the_past
	validate :indate_bigger_tan_outdate
	has_many :markers
	
	def expiration_date_cannot_be_in_the_past
		if outdate.present? && outdate < Time.now
			errors.add(:outdate, "La fecha de vencimiento no puede estar en el pasado ")
		end
	end


	def indate_bigger_tan_outdate
		if indate > outdate
			errors.add(:indate, "La fecha de lanzamiento no puede ser mas lejana que la de vencimiento ")
		end
	end
end

app/models/category.rb
class Category < ApplicationRecord

	has_many :books
end

app/models/commentary.rb
class Commentary < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :book
  belongs_to :profile
end

app/models/genre.rb
class Genre < ApplicationRecord
	has_many :books
end

app/models/marker.rb
class Marker < ApplicationRecord
  belongs_to :capitulo
  belongs_to :profile
  belongs_to :book
end

app/models/notice.rb
class Notice < ApplicationRecord
       has_one_attached :image

        validates_uniqueness_of :titulo, :on => :create
   		validates_uniqueness_of :titulo, :on => :update

end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  validates_uniqueness_of :name, :on => :update
  has_many :votes
  has_many :favorites
  has_many :markers
  has_many :seelaters

end

app/models/seelater.rb
class Seelater < ApplicationRecord
  belongs_to :book
  belongs_to :profile
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :card, length: {is: 16, message: " debe tener 16 números"}
  has_many :profiles
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
end

app/models/vote.rb
class Vote < ApplicationRecord
	belongs_to :profile
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!

  def new
    if current_user.familiar
      if current_user.profiles.size > 3
        redirect_to profiles_path
      end
    else
      if current_user.profiles.size > 1
        redirect_to profiles_path
      end
    end 
    @profile=Profile.new
  end


  def create
		@profile = Profile.new(profile_params)
    @profile.user_id = current_user.id

    yaExiste = false;
    current_user.profiles.each do |p|
      if(p.name == @profile.name)
        yaExiste = true;
      end
    end

    if(current_user.profiles.size < 4)
      if(not yaExiste)
        
        if (@profile.save)
    			flash[:notice] = "El perfil se creo exitosamente"
          redirect_to profiles_path
    		else
    			flash.now[:alert] = 'Ocurrió un error'
          render :new
    		end
      else
        flash.now[:alert] = 'Ya existe ese perfil'
        render :new
      end
    else
      flash.now[:alert] = 'Ya tienes muchos perfiles'
      render :new
    end
	end
    def destroy
      @profile = Profile.find params[:id]
      if current_user.profiles.size > 1
        Commentary.where(profile_id:@profile.id).all.each do |a|
          a.destroy
        end
        @profile.destroy
        session[:profile_id] = nil
        redirect_to profiles_path
      end
    end

  	def profile_params
  		params.require(:profile).permit(:name,:kids,:picture)
  	end

    def show
  		@profile = Profile.find params[:id]
  	end

    def edit

       @profile = Profile.find params[:id]
    end

    def update

    @profile = Profile.find params[:id]
    if(@profile.update(params.require(:profile).permit!))
      redirect_to profiles_path
      flash[:notice] = "Cambios realizados con éxito"
    else
      flash.now[:alert] = 'Ya existe un perfil con ese nombre'
      render :edit
    end

    end

    def index
      if(session[:profile_id] == nil)
        redirect_to profiles_select_path
      else
        @profiles = current_user.profiles
      end
    end

    def select
      if current_user.profiles.size == 0
        redirect_to new_profile_path
      else
        @profiles = current_user.profiles
      end
    end
    def cambiar
      session[:profile_id] = params[:perfil].to_i
      if(session[:profile_id] == nil)
        sign_out current_user
      else
        flash[:notice] = "Seleccionaste perfil correctamente"
      end
      redirect_to root_path
    end
    def cambiarplan1

      if(current_user.familiar == false)
        redirect_to profiles_selectplan_path 
        flash[:alert] = "Usted ya posee este Plan de suscripcion, Seleccione uno Nuevo!!"
      else

       if(current_user.profiles.count > 2)
         flash[:alert] = "Usted no cumple las condiciones para cambiarse al nuevo plan, el mismo requiere como maximo 2 perfiles, usted posee muchos, por favor elimine algunos antes de poder continuar"
         redirect_to profiles_path
       else
         @u=User.find(current_user.id)
         @u.familiar = false
         @u.save
         redirect_to profiles_path
         flash[:notice] = "Felicitaciones ha cambiado su plan de suscripcion, Su nuevo Plan es ahora ESTANDAR"
        end
      end
    end
    def cambiarplan2
      if(current_user.familiar == true)
        redirect_to profiles_selectplan_path 
        flash[:alert] = "Usted ya posee este Plan de suscripcion, Seleccione uno Nuevo!!"
      else
        @u=User.find(current_user.id)
        @u.familiar = true
        @u.save
        redirect_to profiles_path
        flash[:notice] = "Felicitaciones ha cambiado su plan de suscripcion, Su nuevo Plan es ahora FAMILIAR"
      end
    end
    def selectplan
      @profile = session[:profile_id]
    end

    def cambiartarjeta
      @user = current_user
      @user.card = nil
      @user.cvv = nil
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/capitulos_helper.rb
module CapitulosHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/markers_helper.rb
module MarkersHelper
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/seelaters_helper.rb
module SeelatersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/profiles/_header.html.erb
<header>
  <%= link_to image_tag("logo.png") , books_path, :id=>"logo"%>
  <input type="checkbox" id="nav-check">
    <div class="nav-btn">
    <label for="nav-check">
      <span></span>
      <span></span>
      <span></span>
    </label>
  </div>
  <div id="navGeneral">
  <nav id="navPag">
    <ul>
      <li><%= link_to 'Inicio', books_path %></li>
      <li><%= link_to 'Novedades',notices_path %></li>
      <li id="favoritos"><%= link_to '✰Favoritos✰',favorites_path %></li>
      <li id="verMasTarde"><%= link_to '⌛ Ver mas tarde',seelaters_path %></li>
    </ul>
  </nav>
  <nav id="navCuenta">
    <ul>

       <li><%= link_to "Cerrar Sesión", destroy_user_session_path , :method => 'delete' %></li>
      <li><%= link_to 'Cuenta', profiles_path %></li>

      <% if current_user.admin? %>
        <li> <%= link_to('Administrar', books_indexadmin_path) %></li>
      <% end %>


    </ul>
  </nav>
  </div>
</header>

app/views/profiles/cambiar.html.erb
<%= session[:profile_id] %>

app/views/profiles/cambiarplan1.html.erb
<% session[:profile_id] %>

app/views/profiles/cambiarplan2.html .erb
<% session[:profile_id] %>

app/views/profiles/cambiartarjeta.html.erb
<%= render 'header' %>

<% if flash[:alert] %>
        <div class="alertaMala"> <%= alert %> </div>
      <% end %>
      <% if flash[:notice] %>   
          <div class="alertaBuena"> <%= notice %> </div>
      <% end %>


<div class="form_log_in">


<h2 class="titulo">Editar Tarjeta de Crédito</h2>

<%= form_for(@user, url: registration_path(@user), html: { method: :put }) do |f| %>
	<div class="field">
	  <%= f.label :card, 'Numero de tarjeta'%><br />
      <%= f.number_field :card, autocomplete: "Numero de tarjeta",required: true%>
    </div>
    <div class="field">
      <%= f.label :cvv, 'Codigo de seguridad (CVV)' %><br />
      <%= f.number_field :cvv, autocomplete: "Codigo de seguridad",required: true %>
    </div>
    <div class="field">
      <%= f.label :vencimiento , {:use_month_names => ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre']}, 'Fecha de vencimiento' %> <br />   
      <%= f.date_select :vencimiento ,required: true, start_year: 2019, end_year: 2040%>
    </div>

  <div class="field">
    <%= f.label :current_password , 'Contraseña actual'%> <i>(necesitamos tu contraseña actual para confirmar los cambios)</i><br />
    <%= f.password_field :current_password, autocomplete: "Contraseña actual" ,required: true%>
  </div>

  <div class="actions">
    <%= f.submit "Actualizar" %>
  </div>
<% end %>

</div>
<%= link_to("Volver",profiles_path) %>


<style type="text/css">
	
.field{
	margin: 5% 0;
}
.field input{
	display: block;
	margin: auto;
}

</style>

app/views/profiles/edit.html.erb
<%= render 'header' %>
<% if flash[:alert] %>
        <div class="alertaMala"> <%= alert %> </div>
      <% end %>
      <% if flash[:notice] %>   
          <div class="alertaBuena"> <%= notice %> </div>
      <% end %>


<div class="form_log_in">

  <h2 class="titulo">Editar perfil</h2>

  <%= form_for @profile, html: {multipart: true} do |b| %>
    <div class="field">
    <%= b.label :name, 'Nombre' %><br>
		<%= b.text_field :name , placeholder:'Ingrese aqui el nombre del perfil',required: true%>
    </div>

    <div class="field">
    <%= b.label :kids, 'Kids' %> <br />
    <%= b.check_box :kids %> <br />
    </div>


<div class="seleccionarAvatar">

  <%= b.radio_button :picture, "001.png", id: "avatarRadio1", checked: true%>
  <label for="avatarRadio1"><%= image_tag "001.png", class: "avatarImagen"%></label>
  <%= b.radio_button :picture, "002,png", id: "avatarRadio2"%>
  <label for="avatarRadio2"><%= image_tag "002.png", class: "avatarImagen"%></label>
  <%= b.radio_button :picture, "003.png", id: "avatarRadio3"%>
  <label for="avatarRadio3"><%= image_tag "003.png", class: "avatarImagen"%></label>
  <%= b.radio_button :picture, "004.png", id: "avatarRadio4"%>
  <label for="avatarRadio4"><%= image_tag "004.png", class: "avatarImagen"%></label>
             <%= b.radio_button :picture, "005.png", id: "avatarRadio5"%>
  <label for="avatarRadio5"><%= image_tag "005.png", class: "avatarImagen"%></label>
             <%= b.radio_button :picture, "006.png", id: "avatarRadio6"%>
  <label for="avatarRadio6"><%= image_tag "006.png", class: "avatarImagen"%></label>
             <%= b.radio_button :picture, "007.png", id: "avatarRadio7"%>
  <label for="avatarRadio7"><%= image_tag "007.png", class: "avatarImagen"%></label>
             <%= b.radio_button :picture, "008.png", id: "avatarRadio8"%>
  <label for="avatarRadio8"><%= image_tag "008.png", class: "avatarImagen"%></label>
             <%= b.radio_button :picture, "009.png", id: "avatarRadio9"%>
  <label for="avatarRadio9"><%= image_tag "009.png", class: "avatarImagen"%></label>
             <%= b.radio_button :picture, "010.png", id: "avatarRadio10"%>
 <label for="avatarRadio10"><%= image_tag "010.png", class: "avatarImagen"%></label>
             <%= b.radio_button :picture, "011.png", id: "avatarRadio11"%>
 <label for="avatarRadio11"><%= image_tag "011.png", class: "avatarImagen"%></label>
             <%= b.radio_button :picture, "012.png", id: "avatarRadio12"%>
 <label for="avatarRadio12"><%= image_tag "012.png", class: "avatarImagen"%></label>
             <%= b.radio_button :picture, "013.png", id: "avatarRadio13"%>
 <label for="avatarRadio13"><%= image_tag "013.png", class: "avatarImagen"%></label>
             <%= b.radio_button :picture, "014.png", id: "avatarRadio14"%>
 <label for="avatarRadio14"><%= image_tag "014.png", class: "avatarImagen"%></label>
             <%= b.radio_button :picture, "015.png", id: "avatarRadio15"%>
 <label for="avatarRadio15"><%= image_tag "015.png", class: "avatarImagen"%></label>
             <%= b.radio_button :picture, "016.png", id: "avatarRadio16"%>
 <label for="avatarRadio16"><%= image_tag "016.png", class: "avatarImagen"%></label>
             <%= b.radio_button :picture, "017.png", id: "avatarRadio17"%>
 <label for="avatarRadio17"><%= image_tag "017.png", class: "avatarImagen"%></label>
             <%= b.radio_button :picture, "018.png", id: "avatarRadio18"%>
 <label for="avatarRadio18"><%= image_tag "018.png", class: "avatarImagen"%></label>
             <%= b.radio_button :picture, "019.png", id: "avatarRadio19"%>
 <label for="avatarRadio19"><%= image_tag "019.png", class: "avatarImagen"%></label>
             <%= b.radio_button :picture, "020.png", id: "avatarRadio20"%>
 <label for="avatarRadio20"><%= image_tag "020.png", class: "avatarImagen"%></label>
             <%= b.radio_button :picture, "021.png", id: "avatarRadio21"%>
 <label for="avatarRadio21"><%= image_tag "021.png", class: "avatarImagen"%></label>
             <%= b.radio_button :picture, "022.png", id: "avatarRadio22"%>
 <label for="avatarRadio22"><%= image_tag "022.png", class: "avatarImagen"%></label>
             <%= b.radio_button :picture, "023.png", id: "avatarRadio23"%>
 <label for="avatarRadio23"><%= image_tag "023.png", class: "avatarImagen"%></label>
             <%= b.radio_button :picture, "024.png", id: "avatarRadio24"%>
 <label for="avatarRadio24"><%= image_tag "024.png", class: "avatarImagen"%></label>
             <%= b.radio_button :picture, "025.png", id: "avatarRadio25"%>
 <label for="avatarRadio25"><%= image_tag "025.png", class: "avatarImagen"%></label>
             <%= b.radio_button :picture, "026.png", id: "avatarRadio26"%>
 <label for="avatarRadio26"><%= image_tag "026.png", class: "avatarImagen"%></label>
             <%= b.radio_button :picture, "027.png", id: "avatarRadio27"%>
 <label for="avatarRadio27"><%= image_tag "027.png", class: "avatarImagen"%></label>
             <%= b.radio_button :picture, "028.png", id: "avatarRadio28"%>
 <label for="avatarRadio28"><%= image_tag "028.png", class: "avatarImagen"%></label>
             <%= b.radio_button :picture, "029.png", id: "avatarRadio29"%>
 <label for="avatarRadio29"><%= image_tag "029.png", class: "avatarImagen"%></label>
             <%= b.radio_button :picture, "030.png", id: "avatarRadio30"%>
 <label for="avatarRadio30"><%= image_tag "030.png", class: "avatarImagen"%></label>

</div>

    <div class="actions">
      <%= b.submit "Guardar" %>
    </div>
  <% end %>

</div>




 <div class="form_log_in">

    <%= link_to 'Borrar Perfil', @profile, method: :delete, class: "BorrarPefil" , data: {confirm: "Estas seguro?"}%>

  </div>


<%= link_to("Volver",profiles_path) %>

app/views/profiles/index.html.erb
<%= render 'header' %>

<% if flash[:alert] %>
        <div class="alertaMala"> <%= alert %> </div>
      <% end %>
      <% if flash[:notice] %>   
          <div class="alertaBuena"> <%= notice %> </div>
      <% end %>


<div class="indexPerfiles">

	<div class="contenedor">
		<h1 class="titulo">
			Cuenta
		</h1>
	</div>

	<div class="contenedor">
		<div class="tema">
			<h2>Informacion de la cuenta</h2>
		</div>
		<div class="contenido">
			<div class="campo"><span class="tit">Nombre: </span> <%= current_user.name %> </div>
			<div class="campo"><span class="tit">Apellido: </span> <%= current_user.surname %> </div>
			<div class="campo"><span class="tit">e-mail: </span> <%= current_user.email %> </div>
			<div class="campo"><span class="tit">Fecha de nacimiento: </span> <%= current_user.date_of_birth.strftime("%d/%m/%Y") %> </div>
			<div class="campo"><span class="tit">Direccion: </span> <%= current_user.address %> </div>
			<div class="campo">
				<span class="tit">Numero de tarjeta: </span> 
				**** **** **** <%= current_user.card % 10000 %> 
			</div>
			<%= link_to "Editar cuenta", edit_user_registration_path%>
		</div>
	</div>

	<div class="contenedor">
		<div class="tema">
			<h2>Suscripcion</h2>
		</div>
		<div class="contenido">
			<div class="campo">
				<span class="tit">Suscripcion: </span> 
					<% if current_user.familiar %>
						Familiar 
					<% else %>
						Estandar
					<% end %>
				<span class="right"><%= link_to "Cambiar", profiles_selectplan_path %></span>
			</div>

		</div>
	</div>


	<div class="contenedor">
		<div class="tema">
			<h2>Perfil Actual</h2>
		</div>
		<div class="contenido">
			<div class="campo">
				<%= image_tag Profile.find(session[:profile_id]).picture , class: "imagenPerfil"%>
				<%= Profile.find(session[:profile_id]).name %> 
				<span class="right"><%= link_to "Cambiar", profiles_select_path %></span>
			</div>
		</div>
	</div>

	<div class="contenedor">
		<div class="tema">
			<h2>Perfiles</h2>
		</div>
		<div class="contenido">

			<% @profiles.where(kids: false).each do |p| %>

				<div class="campo">
					<%= image_tag p.picture , class: "imagenPerfil"%>
					<%= p.name %>
					<span class="right"><%= link_to "Editar", edit_profile_path(p) %></span>
				</div>

			<% end %>
			
		</div>
	</div>


	<div class="contenedor">
		<div class="tema">
			<h2>Perfiles KIDS</h2>
		</div>
		<div class="contenido">

			<% @profiles.where(kids: true).each do |p| %>

				<div class="campo">
					
					<%= image_tag p.picture , class: "imagenPerfil"%>
					<%= p.name %>
					<span class="right"><%= link_to "Editar", edit_profile_path(p) %></span>
				</div>

			<% end %>
			<% if current_user.familiar %>
				<% if current_user.profiles.size < 4 %>
					<%= link_to "Nuevo perfil", new_profile_path, class: "nuevoPerfil"%>
				<% end %>
			<% else %>
				<% if current_user.profiles.size < 2 %>
					<%= link_to "Nuevo perfil", new_profile_path, class: "nuevoPerfil"%>
				<% end %>
			<% end %>
		</div>
	</div>
</div>

app/views/profiles/select.html.erb
<div class="cosoGigante">
	
	<h1>Selecciona un perfil</h1>

	<div class="lista">
	<% @profiles.each do |p| %>

		<a href="<%= profiles_cambiar_path%>?perfil=<%=p.id.to_s%>" class="nombreEImagen">
			
			<%= image_tag p.picture %>
			<span class="nombrePerfil"><%=p.name%></span>
			
		</a>

	<% end %>
	</div>

	<% if flash[:alert] %>
        <div class="alertaMala"> <%= alert %> </div>
      <% end %>
      <% if flash[:notice] %>   
          <div class="alertaBuena"> <%= notice %> </div>
      <% end %>


</div>

app/views/profiles/selectplan.html.erb
<div class="cosoGigante">
	
	<h1 class="tituloPrincipal">Selecciona el Plan que Deseas Tener</h1>

	<div class="lista2">
	<%= link_to "Plan Estandar" , profiles_cambiarplan1_path , class: "opciones"%>
	<%= link_to "Plan Familiar" , profiles_cambiarplan2_path , class: "opciones"%>
	<p class="lista3"><%= link_to "No Gracias, Deseo mantener mi suscripcion actual !" , profiles_path %></p>
	</div>

	<% if flash[:alert] %>
        <div class="alertaMala"> <%= alert %> </div>
      <% end %>
      <% if flash[:notice] %>   
          <div class="alertaBuena"> <%= notice %> </div>
      <% end %>

</div>

app/views/profiles/show.html.erb
<%= render 'header' %>

<% if flash[:alert] %>
        <div class="alertaMala"> <%= alert %> </div>
      <% end %>
      <% if flash[:notice] %>   
          <div class="alertaBuena"> <%= notice %> </div>
      <% end %>


<div class="showPerfiles">

	<div class="contenedor">
		<h1>
			Perfil: <%= @profile.name%>
		</h1>
	</div>

	<% if @profile.kids %>
	<div class="contenedor">
		<h2>
			Kids
		</h2>
	</div>
	<% end %>

	<div class="contenedor">
		<h2>Favoritos</h2>
		<h5>proximamente..</h5>
	</div>

	<div class="contenedor">
		<%= link_to 'Borrar', @profile, method: :delete %>
		<%= link_to "Editar", edit_profile_path(@profile) %>
	</div>
	
</div>