config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: { confirmations: 'confirmations' }
  root 'books#index'
  get '/books/indexadmin', to: 'books#indexadmin', as: 'books_indexadmin'
  get '/books/showadmin/:id', to: 'books#showadmin', as: 'books_showadmin'
  get '/profiles/select', to: 'profiles#select', as: 'profiles_select'
  get '/profiles/cambiar', to: 'profiles#cambiar', as: 'profiles_cambiar'
  get '/profiles/selectplan', to: 'profiles#selectplan', as: 'profiles_selectplan'
  get '/profiles/cambiarplan1', to: 'profiles#cambiarplan1', as: 'profiles_cambiarplan1'
  get '/profiles/cambiarplan2', to: 'profiles#cambiarplan2', as: 'profiles_cambiarplan2'
  get '/profiles/cambiartarjeta', to: 'profiles#cambiartarjeta', as: 'profiles_cambiartarjeta'
  resources :notices
  resources :favorites
  resources :markers
  resources :seelaters
  resources :books
  resources :profiles
  resources :welcome
  resources :books do
  	resources :capitulos
  end
  resources :commentaries
  resources :votes
  resources :authors
  get '/books/:book_id/capitulos/:id/borrar', to: 'capitulos#borrar', as: 'borrar_book_capitulo'

end

app/models/author.rb
class Author < ApplicationRecord
  has_and_belongs_to_many :books
end

app/models/authors_book.rb
class AuthorsBook < ApplicationRecord
  belongs_to :book
  belongs_to :author
end

app/models/book.rb
class Book < ApplicationRecord

   validate :indate_bigger_tan_outdate
   has_and_belongs_to_many :authors
   has_one_attached :image
   has_many :favorites
   has_many :seelaters
   has_many :markers
   belongs_to :genre
   belongs_to :category
   validates_uniqueness_of :isbn, :on => :create
   validates_uniqueness_of :isbn, :on => :update

   has_many :capitulos
   has_many :commentaries



  def indate_bigger_tan_outdate
    if indate > outdate
      errors.add(:indate, "La fecha de lanzamiento no puede ser mas lejana que la de vencimiento ")
    end
  end

end

app/models/capitulo.rb
class Capitulo < ApplicationRecord
	belongs_to :book
	validate :expiration_date_cannot_be_in_the_past
	validate :indate_bigger_tan_outdate
	has_many :markers
	
	def expiration_date_cannot_be_in_the_past
		if outdate.present? && outdate < Time.now
			errors.add(:outdate, "La fecha de vencimiento no puede estar en el pasado ")
		end
	end


	def indate_bigger_tan_outdate
		if indate > outdate
			errors.add(:indate, "La fecha de lanzamiento no puede ser mas lejana que la de vencimiento ")
		end
	end
end

app/models/category.rb
class Category < ApplicationRecord

	has_many :books
end

app/models/commentary.rb
class Commentary < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :book
  belongs_to :profile
end

app/models/genre.rb
class Genre < ApplicationRecord
	has_many :books
end

app/models/marker.rb
class Marker < ApplicationRecord
  belongs_to :capitulo
  belongs_to :profile
  belongs_to :book
end

app/models/notice.rb
class Notice < ApplicationRecord
       has_one_attached :image

        validates_uniqueness_of :titulo, :on => :create
   		validates_uniqueness_of :titulo, :on => :update

end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  validates_uniqueness_of :name, :on => :update
  has_many :votes
  has_many :favorites
  has_many :markers
  has_many :seelaters

end

app/models/seelater.rb
class Seelater < ApplicationRecord
  belongs_to :book
  belongs_to :profile
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :card, length: {is: 16, message: " debe tener 16 números"}
  has_many :profiles
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
end

app/models/vote.rb
class Vote < ApplicationRecord
	belongs_to :profile
end

app/controllers/capitulos_controller.rb
class CapitulosController < ApplicationController




	def new
		@book = Book.find params[:book_id]

		@capitulo = Capitulo.new
		@capitulo.book_id = params[:book_id]

		@capitulo.numero = @book.capitulos.size + 1

	end
	def create
		@book = Book.find params[:book_id]
  		@capitulo = Capitulo.new(params.require(:capitulo).permit!)
  		@capitulo.book_id = params[:book_id]
		@capitulo.numero = @book.capitulos.size + 1

  		if (@capitulo.save)
			redirect_to root_path

		end

	end
	def edit
		redirect_to root_path unless current_user.admin?

		@book = Book.find params[:book_id]
		@capitulo = Capitulo.find params[:id]


		

	end
	def borrar
		redirect_to root_path unless current_user.admin?

		@capitulo = Capitulo.find params[:id]
		@capitulo.destroy
			
		redirect_to books_path
		flash[:notice] = "Capitulo borrado exitosamente"
	end

	

	def update
		@capitulo = Capitulo.find params[:id]
		redirect_to root_path unless current_user.admin?
		if(@capitulo.update(params.require(:capitulo).permit!))
			redirect_to books_indexadmin_path
			flash[:notice] = "Cambios realizados con éxito"
		else
			flash.now[:alert] = @capitulo.errors.full_messages.first
			render :edit
		end
	end
	def index
		@perfil = Profile.find(session[:profile_id])
		@book = Book.find params[:book_id]
		@capitulos = @book.capitulos.where("? < outdate AND ? > indate", Time.now,Time.now)
	end
	def show
		@capitulo = Capitulo.find params[:id]
		if (@capitulo.indate > Time.now or @capitulo.outdate < Time.now)
			@capitulo = nil
		end
		@book = Book.find params[:book_id]
		if (Seelater.where(book_id:@book.id,profile_id:session[:profile_id]).all.count > 0)
			Seelater.where(book_id:@book.id,profile_id:session[:profile_id]).last.destroy
		end
		if(current_user.profiles.find(session[:profile_id]).markers.where(capitulo_id: @capitulo.id).size == 0)
			@marker = Marker.new(capitulo_id: @capitulo.id, profile_id: session[:profile_id], book_id: @capitulo.book_id)
		else
			@marker = current_user.profiles.find(session[:profile_id]).markers.where(capitulo_id: @capitulo.id).first
		end
	end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/capitulos_helper.rb
module CapitulosHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/markers_helper.rb
module MarkersHelper
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/seelaters_helper.rb
module SeelatersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/capitulos/_header.html.erb
<header>
  <%= link_to image_tag("logo.png") , books_path, :id=>"logo"%>
  <input type="checkbox" id="nav-check">
    <div class="nav-btn">
    <label for="nav-check">
      <span></span>
      <span></span>
      <span></span>
    </label>
  </div>
  <div id="navGeneral">
  <nav id="navPag">
    <ul>
      <li><%= link_to 'Inicio', books_path %></li>
      <li><%= link_to 'Novedades',notices_path %></li>
      <li id="favoritos"><%= link_to '✰Favoritos✰',favorites_path %></li>
      <li id="verMasTarde"><%= link_to '⌛ Ver mas tarde',seelaters_path %></li>
    </ul>
  </nav>
  <nav id="navCuenta">
    <ul>

       <li><%= link_to "Cerrar Sesión", destroy_user_session_path , :method => 'delete' %></li>
      <li><%= link_to 'Cuenta', profiles_path %></li>

      <% if current_user.admin? %>
        <li> <%= link_to('Administrar', books_indexadmin_path) %></li>
      <% end %>


    </ul>
  </nav>
  </div>
</header>

app/views/capitulos/edit.html.erb
<%= render 'header' %>



<% if flash[:alert] %>
        <div class="alertaMala"> <%= alert %> </div>
      <% end %>
      <% if flash[:notice] %>
          <div class="alertaBuena"> <%= notice %> </div>
      <% end %>

<div class="form_log_in">

  <h2 class="titulo"> Capítulo <%= @capitulo.numero %></h2>
  <h3 class="subtitulo"><%= @book.titulo %></h3>


  <%= form_with(model: [@book,@capitulo], local: true) do |c| %>
    <div class="field">
      	<%= c.label :titulo %><br>
		      <%= c.text_field :titulo , placeholder:'Ingrese aqui el titulo del capitulo ',required: true%>
    </div>


    <div class="field">
      	<%= c.label :pdf %><br>
    	<%= c.text_field :pdf ,required: true, placeholder: 'Ingrese el link del pdf',required: true%>
    </div>

    <div class="field field_fecha">
      <%= c.date_select :indate , {:use_month_names => ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre']},required: true, start_year: 2019, end_year: 2040, id: "edad", class: "popeador", onchange: "popear(this)"%>
      <%= c.label :indate , 'Fecha de lanzamiento', id: "edad_label" %>

    </div>
    <div class="field field_fecha">
      <%= c.date_select :outdate , {:use_month_names => ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre']},required: true, start_year: 2019, end_year: 2040, id: "edad", class: "popeador", onchange: "popear(this)"%>
      <%= c.label :outdate , 'Fecha de vencimiento', id: "edad_label" %>


    <div class="actions">
      <%= c.submit "Editar" %>
    </div>
  <% end %>

</div>
<%= link_to("Volver",books_indexadmin_path) %>

app/views/capitulos/index.html.erb
<%= render 'header' %>


<% if flash[:alert] %>
        <div class="alertaMala"> <%= alert %> </div>
      <% end %>
      <% if flash[:notice] %>   
          <div class="alertaBuena"> <%= notice %> </div>
      <% end %>



<div id="listaCapitulos">
<%= link_to "Volver", @book , class:"botonVolver"%>
<% if current_user.admin? %>
    <li> <%= link_to 'Agregar capítulo', new_book_capitulo_path, class:"botonVolver" %></li>
<% end %>


	<% @capitulos.each do |c| %>

		<a href="<%= book_capitulo_path(@book,c) %>" class="cap btn-5">
			<span class="numCap">
				Capítulo: <%= c.numero %>
			</span>
			<span class="tituloCap">
				<%= c.titulo %>
			</span>

      <% if Marker.where(capitulo_id: c.id).where(profile_id: session[:profile_id]).size > 0 %>
          <span class="marcador"></span>
      <% end %>
		</a>

	<% end %>

</div>


<style type="text/css">
	.btn-5,
.btn-5::after {
  -webkit-transition: all 0.3s;
	-moz-transition: all 0.3s;
  -o-transition: all 0.3s;
	transition: all 0.3s;
}

.btn-5 {
	color:#ccc;
  position: relative;
}

.btn-5::before,
.btn-5::after {
  background: #fff;
  content: '';
  position: absolute;
  z-index: -1;
}

.btn-5:hover {
  color: #fff;
}
.btn-5 {
  overflow: hidden;
}

.btn-5::after {
  background-color: #c00;
  height: 100%;
  left: -35%;
  top: 0;
  transform: skew(50deg);
  transition-duration: 0.6s;
  transform-origin: top left;
  width: 0;
}

.btn-5:hover:after {
  height: 100%;
  width: 135%;
}
</style>

app/views/capitulos/new.html.erb
<%= render 'header' %>



<% if flash[:alert] %>
        <div class="alertaMala"> <%= alert %> </div>
      <% end %>
      <% if flash[:notice] %>   
          <div class="alertaBuena"> <%= notice %> </div>
      <% end %>

<div class="form_log_in">

  <h2 class="titulo">Capítulo <%= @capitulo.numero %></h2>
  <h3 class="subtitulo"><%= @book.titulo %></h3>


  <%= form_with(model: [@book,@capitulo], local: true) do |c| %>
    <div class="field">
      	<%= c.label :titulo %><br>
		      <%= c.text_field :titulo , placeholder:'Ingrese aqui el titulo del capitulo ',required: true%>
    </div>


    <div class="field">
      	<%= c.label :pdf %><br>
    	<%= c.text_field :pdf ,required: true, placeholder: 'Ingrese el link del pdf',required: true%>
    </div>

    <div class="field field_fecha">
      <%= c.date_select :indate , {:use_month_names => ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre']},required: true, start_year: 2019, end_year: 2040, id: "edad", class: "popeador", onchange: "popear(this)"%>
      <%= c.label :indate , 'Fecha de lanzamiento', id: "edad_label" %>

    </div>
    <div class="field field_fecha">
      <%= c.date_select :outdate , {:use_month_names => ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre']},required: true, start_year: 2019, end_year: 2040, id: "edad", class: "popeador", onchange: "popear(this)"%>
      <%= c.label :outdate , 'Fecha de vencimiento', id: "edad_label" %>


    <div class="actions">
      <%= c.submit "Agregar" %>
    </div>
  <% end %>

</div>
<%= link_to("Volver",books_indexadmin_path) %>

app/views/capitulos/show.html.erb
<div class="headerPDF">
	<%= link_to "Salir", @book , class: "volverPDF"%>


<% if @capitulo == nil %>
<% controller.redirect_to books_path %>
<% else %>

	<% if @book.capitulos.size > @capitulo.numero and (@book.capitulos.where(numero: @capitulo.numero+1).first.indate < Time.now) and (@book.capitulos.where(numero: @capitulo.numero+1).first.outdate > Time.now)  %> <!-- si hay capitulo siguiente -->
		<%= link_to "Siguiente", book_capitulo_path(@book,@book.capitulos.where(numero: @capitulo.numero+1)[0]) , class: "siguientePDF"%>
	<% end %>
	<% if (current_user.profiles.find(session[:profile_id]).markers.where(capitulo_id: @capitulo.id)).size == 0 %>
		<%= form_for @marker do |b| %>
		<%=  b.hidden_field :capitulo_id %>
		<%=  b.hidden_field :profile_id %>
		<%=  b.hidden_field :book_id %>
		<%=  b.submit "Colocar marcador",  :class => "colocarMarcador" %>
		<% end %>
		<% else %>
			 <%= link_to 'Eliminar marcador', @marker, method: :delete,  :class => "borrarMarcador" %>
		<% end %>
	<% if @capitulo.numero > 1 and (@book.capitulos.where(numero: @capitulo.numero-1).first.indate < Time.now) and (@book.capitulos.where(numero: @capitulo.numero-1).first.outdate > Time.now) %> <!-- si hay capítulo anterior -->
		<%= link_to "Anterior", book_capitulo_path(@book,@book.capitulos.where(numero: @capitulo.numero-1)[0]) , class: "siguientePDF"%>
	<% end %>

</div>


<iframe src="<%= @capitulo.pdf %>" frameborder='0'></iframe>


<div class="cargandoPDF">
	<div class="lds-roller"><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div></div>
</div>
<% end %>