config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: { confirmations: 'confirmations' }
  root 'books#index'
  get '/books/indexadmin', to: 'books#indexadmin', as: 'books_indexadmin'
  get '/books/showadmin/:id', to: 'books#showadmin', as: 'books_showadmin'
  get '/profiles/select', to: 'profiles#select', as: 'profiles_select'
  get '/profiles/cambiar', to: 'profiles#cambiar', as: 'profiles_cambiar'
  get '/profiles/selectplan', to: 'profiles#selectplan', as: 'profiles_selectplan'
  get '/profiles/cambiarplan1', to: 'profiles#cambiarplan1', as: 'profiles_cambiarplan1'
  get '/profiles/cambiarplan2', to: 'profiles#cambiarplan2', as: 'profiles_cambiarplan2'
  get '/profiles/cambiartarjeta', to: 'profiles#cambiartarjeta', as: 'profiles_cambiartarjeta'
  resources :notices
  resources :favorites
  resources :markers
  resources :seelaters
  resources :books
  resources :profiles
  resources :welcome
  resources :books do
  	resources :capitulos
  end
  resources :commentaries
  resources :votes
  resources :authors
  get '/books/:book_id/capitulos/:id/borrar', to: 'capitulos#borrar', as: 'borrar_book_capitulo'

end

app/models/author.rb
class Author < ApplicationRecord
  has_and_belongs_to_many :books
end

app/models/authors_book.rb
class AuthorsBook < ApplicationRecord
  belongs_to :book
  belongs_to :author
end

app/models/book.rb
class Book < ApplicationRecord

   validate :indate_bigger_tan_outdate
   has_and_belongs_to_many :authors
   has_one_attached :image
   has_many :favorites
   has_many :seelaters
   has_many :markers
   belongs_to :genre
   belongs_to :category
   validates_uniqueness_of :isbn, :on => :create
   validates_uniqueness_of :isbn, :on => :update

   has_many :capitulos
   has_many :commentaries



  def indate_bigger_tan_outdate
    if indate > outdate
      errors.add(:indate, "La fecha de lanzamiento no puede ser mas lejana que la de vencimiento ")
    end
  end

end

app/models/capitulo.rb
class Capitulo < ApplicationRecord
	belongs_to :book
	validate :expiration_date_cannot_be_in_the_past
	validate :indate_bigger_tan_outdate
	has_many :markers
	
	def expiration_date_cannot_be_in_the_past
		if outdate.present? && outdate < Time.now
			errors.add(:outdate, "La fecha de vencimiento no puede estar en el pasado ")
		end
	end


	def indate_bigger_tan_outdate
		if indate > outdate
			errors.add(:indate, "La fecha de lanzamiento no puede ser mas lejana que la de vencimiento ")
		end
	end
end

app/models/category.rb
class Category < ApplicationRecord

	has_many :books
end

app/models/commentary.rb
class Commentary < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :book
  belongs_to :profile
end

app/models/genre.rb
class Genre < ApplicationRecord
	has_many :books
end

app/models/marker.rb
class Marker < ApplicationRecord
  belongs_to :capitulo
  belongs_to :profile
  belongs_to :book
end

app/models/notice.rb
class Notice < ApplicationRecord
       has_one_attached :image

        validates_uniqueness_of :titulo, :on => :create
   		validates_uniqueness_of :titulo, :on => :update

end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  validates_uniqueness_of :name, :on => :update
  has_many :votes
  has_many :favorites
  has_many :markers
  has_many :seelaters

end

app/models/seelater.rb
class Seelater < ApplicationRecord
  belongs_to :book
  belongs_to :profile
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :card, length: {is: 16, message: " debe tener 16 números"}
  has_many :profiles
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
end

app/models/vote.rb
class Vote < ApplicationRecord
	belongs_to :profile
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

	before_action :authenticate_user!
	before_action :authenticate_profile


	def new
		redirect_to root_path unless current_user.admin?

		@book=Book.new
		@autor = Author.new

	end

	def create
		redirect_to root_path unless current_user.admin?

		@book = Book.new(book_params)
		@book.punctuation=0
		@book.scores=0
		@book.total=0

		if (@book.save)
			redirect_to @book
			flash[:notice] = "El libro se guardó con éxito"
		else
			flash.now[:alert] =  @book.errors.full_messages.first
			render :new
		end

	end

	def index
		if !(Profile.find(session[:profile_id]).kids)
			if @b = params[:buscador]
				@books = Book.where('titulo LIKE ? AND  outdate > ? AND indate < ?', "%#{@b}%", Time.now , Time.now)
			else
				#@books = Book.all
				@books = Book.where("? < outdate AND ? > indate", Time.now,Time.now)
			end
		else
			if @b = params[:buscador]
				@books = Book.where('titulo LIKE ? AND  outdate > ? AND indate < ?', "%#{@b}%", Time.now , Time.now).where(kids: true)
			else
				#@books = Book.all
				@books = Book.where("? < outdate AND ? > indate", Time.now, Time.now).where(kids: true)
			end
		end
	end
	def indexadmin
		redirect_to root_path unless current_user.admin?
	end
	def showadmin
		redirect_to root_path unless current_user.admin?
		@book = Book.find params[:id]
	end


	def show
		@book = Book.find params[:id]
		if (@book.indate > Time.now or @book.outdate < Time.now)
			@book = nil
		else
			if (Profile.find(session[:profile_id]).kids and !@book.kids)
				@book = nil
			else
				@comentario = Commentary.new(profile_id: session[:profile_id], book_id: @book.id)
				@punto = Vote.new(profile_id: session[:profile_id], isbn: @book.isbn)

				#si ya existe buscarlo y guardarlo en @favorito
				if(current_user.profiles.find(session[:profile_id]).favorites.where(book_id:@book.id).size == 0)
					@favorite = Favorite.new(book_id: @book.id, profile_id: session[:profile_id])
				else
					@favorite = current_user.profiles.find(session[:profile_id]).favorites.where(book_id:@book.id).first
				end
				if(current_user.profiles.find(session[:profile_id]).seelaters.where(book_id:@book.id).size == 0)
					@seelater = Seelater.new(book_id: @book.id, profile_id: session[:profile_id])
				else
					@seelater = current_user.profiles.find(session[:profile_id]).seelaters.where(book_id:@book.id).first
				end
			end
		end
	end

	def edit
		redirect_to root_path unless current_user.admin?

		@book = Book.find params[:id]
		@autor = Author.new

	end

	def destroy
		redirect_to root_path unless current_user.admin?

		@book = Book.find params[:id]
		@book.destroy
		redirect_to books_path
	end

	def update
		redirect_to root_path unless current_user.admin?

		@book = Book.find params[:id]
		if(@book.update(params.require(:book).permit!))
			redirect_to books_indexadmin_path
			flash[:notice] = "Cambios realizados con éxito"
		else
			flash.now[:alert] = @book.errors.full_messages.first

			render :edit
		end
	end

	private

	def book_params
		params.require(:book).permit(:total,:punctuation,:scores,:titulo,:genre_id,:category_id,:kids,:resumen,:indate,:outdate,:picture,:isbn,:editorial,author_ids:[])
	end


end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/capitulos_helper.rb
module CapitulosHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/markers_helper.rb
module MarkersHelper
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/seelaters_helper.rb
module SeelatersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/books/_book.html.erb
<article class="libro">

    <div class="img">
    	<img src="<%= book.picture %>">
    </div>

    <a class="info" href="<%= book_path book.id %>">
      <h3 class="titulo">
        <%= book.titulo %>
      </h3>
    </a>

</article>

app/views/books/_header.html.erb
<header>
  <%= link_to image_tag("logo.png") , books_path, :id=>"logo"%>
  <input type="checkbox" id="nav-check">
    <div class="nav-btn">
    <label for="nav-check">
      <span></span>
      <span></span>
      <span></span>
    </label>
  </div>
  <div id="navGeneral">
  <nav id="navPag">
    <ul>
      <li><%= link_to 'Inicio', books_path %></li>
      <li><%= link_to 'Novedades',notices_path %></li>
      <li id="favoritos"><%= link_to '✰Favoritos✰',favorites_path %></li>
      <li id="verMasTarde"><%= link_to '⌛ Ver mas tarde',seelaters_path %></li>
    </ul>
  </nav>
  <nav id="navCuenta">
    <ul>

       <li><%= link_to "Cerrar Sesión", destroy_user_session_path , :method => 'delete' %></li>
      <li><%= link_to 'Cuenta', profiles_path %></li>

      <% if current_user.admin? %>
        <li> <%= link_to('Administrar', books_indexadmin_path) %></li>
      <% end %>


    </ul>
  </nav>
  </div>
</header>

app/views/books/edit.html.erb
<%= render 'header' %>


<% if flash[:alert] %>
        <div class="alertaMala"> <%= alert %> </div>
      <% end %>
      <% if flash[:notice] %>   
          <div class="alertaBuena"> <%= notice %> </div>
      <% end %>


<div class="form_log_in">

  <h2 class="titulo">Edita un libro</h2>


  <%= form_for @book, html: {multipart: true} do |b| %>
    <div class="field">
        <%= b.label :titulo %><br>
    <%= b.text_field :titulo , placeholder:'Ingrese aqui el titulo del nuevo libro',required: true%>
    </div>

    <div class="form-group">
        <%= b.label :genre_id, 'Genero' %><br>
    <%= b.collection_select :genre_id, Genre.all, :id, :nombre, placeholder:'Ingrese aqui el genero al que corresponde' %>
    </div>

    <div class="form-group">
        <%= b.label :category_id, 'Categoria' %><br>
    <%= b.collection_select :category_id, Category.all, :id, :nombre, placeholder:'Ingrese aqui la Categoria a la que corresponde' %>
    </div>

    <div class="field">
      <%= b.label :resumen %><br>
      <%= b.text_area :resumen , placeholder:'Ingrese la sinopsis del libro',required: true, :class => 'textarea'%>
    </div>

    <div class="field">
        <%= b.label :picture, 'Imagen' %><br>
    <%= b.text_field :picture ,required: true, placeholder: 'Ingrese el link de la Imagen'%>
    </div>

     <div class="field">
        <%= b.label :isbn %><br>
    <%= b.text_field :isbn , placeholder:'Ingrese el numero ISBN', required: true%>
    </div>

     <div class="field">
        <%= b.label :editorial %><br>
    <%= b.text_field :editorial , placeholder:'Ingrese la editorial', required: true%>
    </div>

    <div class="field">
    <%= b.label :kids, 'Kids' %> <br />
    <%= b.check_box :kids %> <br />
    </div>


    <div class="field">
      <%= b.label :author_ids, 'Autores'  %><br>

      <%= b.collection_select :author_ids, Author.all, :id, :autor, {}, class: 'autores', multiple: true ,required: true%>

</div>

<div class="field field_fecha">
  <%= b.date_select :indate , {:use_month_names => ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre']},required: true, start_year: 2019, end_year: 2040, id: "edad", class: "popeador", onchange: "popear(this)"%>
  <%= b.label :indate , 'Fecha de lanzamiento', id: "edad_label" %>

</div>
<div class="field field_fecha">
  <%= b.date_select :outdate , {:use_month_names => ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre']},required: true, start_year: 2019, end_year: 2040, id: "edad", class: "popeador", onchange: "popear(this)"%>
  <%= b.label :outdate , 'Fecha de vencimiento', id: "edad_label" %>

</div>



    <div class="actions">
      <%= b.submit "Confirmar cambios" %>
    </div>
  <% end %>

</div>
<br/>

  <div class="form_log_in">

   <%= form_tag({:controller => "authors", :action => "edit"}, :method => :get) do %>
     <div class="field" >
     Nuevo Autor
    <%= text_field_tag "autor", params[:autor], placeholder: "Ingrese aqui el nombre del nuevo autor!" %>



   <%= submit_tag "Añadir" %>




    </div>
    <% end %>

  </div>





<%= link_to("Volver",books_indexadmin_path) %>

app/views/books/indexadmin.html.erb
<%= render 'header' %>

<% if flash[:alert] %>
        <div class="alertaMala"> <%= alert %> </div>
      <% end %>
      <% if flash[:notice] %>   
          <div class="alertaBuena"> <%= notice %> </div>
      <% end %>


<%= link_to 'Nuevo Libro', new_book_path, :class => "nuevoLibro" %>



<div class="cabecera">
	<p>Libros</p>
</div>


<section class="ListadoLibrosAdmin">

		<article class="libro">
			<div class="encabezado responsive2">Imagen</div>
			<div class="encabezado responsive2">Titulo</div>
			<div class="encabezado responsive">Resumen</div>
			<div class="encabezado responsive">Autores</div>
			<div class="encabezado responsive">Genero</div>
			<div class="encabezado responsive">Categoria</div>
			<div class="encabezado responsive">ISBN</div>
			<div class="encabezado responsive">Editorial</div>
			<div class="encabezado responsive">Lanzamiento</div>
			<div class="encabezado responsive">Caducidad</div>

		</article>

	<% Book.all.each do |b| %>

		<article class="libro">
		

			<div class="imagen responsive2"><%= link_to image_tag(b.picture), books_showadmin_path(b.id) %></div>
			<div class="titulo responsive2"><%= b.titulo %></div>
			<div class="resumen responsive"><%= b.resumen %></div>
			<div class="autor responsive">
				<% b.authors.each do |a| %>
				<%= a.autor %><br>
				<% end %>
			</div>
			<div class="autor responsive"><%= Genre.find(b.genre_id).nombre %></div>
			<div class="autor responsive"><%= Category.find(b.category_id).nombre %></div>
			<div class="isbn responsive"><%= b.isbn %></div>
			<div class="autor responsive"><%= b.editorial %></div>
			<div class="autor responsive">	<%= b.indate.strftime("%d/%m/%Y") %></div>
			<div class="autor responsive">	<%= b.outdate.strftime("%d/%m/%Y") %></div>

		</article>


	<% end %>
</section>



<%= link_to 'Nueva noticia', new_notice_path, :class => "nuevoLibro" %>

<div class="cabecera">
	<p>Noticias</p>
</div>

<section class="ListadoLibrosAdmin">

		<article class="libro">
			<div class="encabezado responsive2">Imagen</div>
			<div class="encabezado responsive2">Titulo</div>
			<div class="encabezado responsive">Cuerpo</div>
			<div class="encabezado responsive">Fecha</div>
			<div class="encabezado responsive2">Opciones</div>

		</article>

	<% Notice.all.each do |n| %>

		<article class="libro">

			<div class="imagen responsive2"><img src="<%= n.picture %>"></div>
			<div class="titulo responsive2"><%= n.titulo %></div>
			<div class="resumen responsive"><%= n.cuerpo %></div>
			<div class="fecha responsive"> <%= n.created_at.strftime("%Y-%m-%d") %></div>
			<div class="opciones responsive2">
			<%= link_to 'Editar', edit_notice_path(n)%>
			<%= link_to 'Eliminar', n, method: :delete %>
			</div>

		</article>


	<% end %>
</section>

app/views/books/show.html.erb
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>

<script src='https://dl.dropboxusercontent.com/s/j07tdncc5vgoglb/bootstrap.min.js?dl=0' type='text/javascript'></script>

<script src='https://dl.dropboxusercontent.com/s/ykdgu2edci3bd42/starrr.js?dl=0' type='text/javascript'></script>

<link href="http://netdna.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet"/>

<%= render 'header' %>


<% if flash[:alert] %>
        <div class="alertaMala"> <%= alert %> </div>
      <% end %>
      <% if flash[:notice] %>   
          <div class="alertaBuena"> <%= notice %> </div>
      <% end %>


<section id="main">
<% if @book == nil %>
  <% controller.redirect_to books_path %>
<% else %>

  <div class="tituloImagenYResumen">
  	<h1 class="titulo"><%= @book.titulo %></h1>
  	<img src="<%= @book.picture %>">

  	<p class="resumen"><%= @book.resumen %></p>
  </div>

	<div class="botones">
	<%= link_to 'Capítulos', book_capitulos_path(@book) , :class => "leerAhora"%>
	<%if(current_user.profiles.find(session[:profile_id]).favorites.where(book_id:@book.id).size == 0) %>
		 <%= form_for @favorite do |b| %>
		 <%=  b.hidden_field :book_id %>
		 <%=  b.hidden_field :profile_id %>
     	 <%= b.submit "Agregar a favoritos",  :class => "agregarLista" %>
     	 <% end %>
	<% else %>
		 <%= link_to 'Eliminar de lista de favoritos', @favorite, method: :delete,  :class => "eliminarLista" %>
	<% end %>
	<%if(current_user.profiles.find(session[:profile_id]).seelaters.where(book_id:@book.id).size == 0) %>
		 <%= form_for @seelater do |b| %>
		 <%=  b.hidden_field :book_id %>
		 <%=  b.hidden_field :profile_id %>
			 <%= b.submit "Agregar a ver más tarde",  :class => "agregarLista" %>
			 <% end %>
	<% else %>
		 <%= link_to 'Eliminar de ver más tarde', @seelater, method: :delete,  :class => "eliminarLista" %>
	<% end %>
	</div>

  <div class="infoDelLibro">
	<p class="autor"> <span style="color:white;">Autor/es:  </span> 	<% @book.authors.each do |a| %>
                									<%= a.autor + "." %>
                									<% end %>
	</p>
	<p class="autor"> <span style="color:white;">Genero Literario: </span>  <%= Genre.find(@book.genre_id).nombre %></p>
	<p class="autor"> <span style="color:white;">Categoria: </span>  <%= Category.find(@book.category_id).nombre %></p>
   	<p class="autor"> <span style="color:white;">Editorial: </span>   <%= @book.editorial %></p>
  </div>
</section>



   	<% if(Profile.find(session[:profile_id]).votes.where(isbn:@book.isbn).count == 0) %>

   		<% variable = 0 %>

   	<% else %>

   		<% variable = Profile.find(session[:profile_id]).votes.where(isbn:@book.isbn).last.punctuation %>

   	<% end %>


<section id="seccion2">
    <div class="puntuacionEstrellas">
    <p class="autor"><span style="color:white;">Valoración del Público:</span></p>

     <span>
     <% i = @book.punctuation %>
     <% i.times do %>
        <img class="inputstar" src="<%= asset_path 'estrella1.png' %>">
      <% end %>
      <% (5-i).times do %>
        <img class="inputstar" src="<%= asset_path 'estrella2.png' %>">
       <% end %>


     </span>
       <p class="voto">
     <%= @book.scores %> votos
     </p>
     </div>



     <div class="puntuarEstrellas">
      <p class="autor"><span style="color:white;">Tu puntuación:</span></p>

      <span>
     <% @punto.punctuation = 1 %>
     <%= form_for @punto , html: {multipart: true} do |p| %>
     <%= p.hidden_field :profile_id %>
     <%= p.hidden_field :isbn %>
     <%= p.hidden_field :punctuation %>
     <% if(variable > 0) %>
     <%= image_submit_tag ("estrella1.png") , :class => "inputstar" %>
     <% else %>
     <%= image_submit_tag ("estrella2.png") , :class => "inputstar" %>
     <% end %>
     <% end %>

     <% @punto.punctuation = 2 %>
     <%= form_for @punto, html: {multipart: true} do |p| %>
     <%= p.hidden_field :profile_id %>
     <%= p.hidden_field :isbn %>
     <%= p.hidden_field :punctuation %>
     <% if(variable > 1) %>
     <%= image_submit_tag ("estrella1.png") , :class => "inputstar" %>
     <% else %>
     <%= image_submit_tag ("estrella2.png") , :class => "inputstar" %>
     <% end %>
     <% end %>

     <% @punto.punctuation = 3 %>
     <%= form_for @punto, html: {multipart: true} do |p| %>
     <%= p.hidden_field :profile_id %>
     <%= p.hidden_field :isbn %>
     <%= p.hidden_field :punctuation %>
     <% if(variable > 2) %>
     <%= image_submit_tag ("estrella1.png") , :class => "inputstar" %>
     <% else %>
     <%= image_submit_tag ("estrella2.png") , :class => "inputstar" %>
     <% end %>
     <% end %>

     <% @punto.punctuation = 4 %>
     <%= form_for @punto, html: {multipart: true} do |p| %>
     <%= p.hidden_field :profile_id %>
     <%= p.hidden_field :isbn %>
     <%= p.hidden_field :punctuation %>
      <% if(variable > 3) %>
     <%= image_submit_tag ("estrella1.png") , :class => "inputstar" %>
     <% else %>
     <%= image_submit_tag ("estrella2.png") , :class => "inputstar" %>
     <% end %>
     <% end %>

     <% @punto.punctuation = 5 %>
     <%= form_for @punto, html: {multipart: true} do |p| %>
     <%= p.hidden_field :profile_id %>
     <%= p.hidden_field :isbn %>
     <%= p.hidden_field :punctuation %>
      <% if(variable > 4) %>
     <%= image_submit_tag ("estrella1.png") , :class => "inputstar" %>
     <% else %>
     <%= image_submit_tag ("estrella2.png") , :class => "inputstar" %>
     <% end %>
     <% end %>
     </span>

      <% if(variable == 0) %>
      <p class="vote1">
         Aun no has puntuado este libro!!
      </p>
      <% else %>
      <p class="vote2">
           Ya has puntuado este libro
      </p>
      <% end %>
      </div>








 </section>





 <section id="seccion3">

 		<p class="cantComentarios"><%= @book.commentaries.count %> Comentarios</p>


    <div class="formComentar">
   		<span class="comment">
   		   Vas a comentar publicamente como <%= Profile.find(session[:profile_id]).name %>
  		</span>


      <%= form_for @comentario, html: {multipart: true} do |g| %>
        <%= g.hidden_field :profile_id %>
        <%= g.hidden_field :book_id %>
        <div class="field">
          <%= g.text_area :comment , placeholder:'Ingrese aqui su comentario',required: true, maxlength:"100" , :class => "textarea_input"%>
        </div>

        <div class="field">
          <%= g.submit "Comentar", class: "btn-comentar"%>
        </div>
      <% end %>
    </div>


    <div class="listaComentarios">
    	<% @book.commentaries.order(created_at: :desc).each do |c| %>

        <div class="cajaComentario">

            <div class="infoComentario">
        		<%= image_tag Profile.find(c.profile_id).picture %>


            <span class="nombre">
     				   <%= Profile.find(c.profile_id).name %>
     			  </span> &nbsp;

            <span class="fecha">
          			     <%
                		tiempoEnSegundos = Time.now - c.created_at
                		tiempoEnHoras = tiempoEnSegundos / 3600
                		if tiempoEnHoras < 1%>
                 		 Ahora
                 		 <%
                		elsif tiempoEnHoras < 24
                		  t = tiempoEnHoras.to_i %>

                 		 Hace <%= t %> Horas

                 		 <% else
                		  t = (tiempoEnHoras/24).to_i %>

                 		 Hace <%= t %> Dias

                 		 <% end %>

            </span>


           	<% if(current_user.admin? or c.profile_id==session[:profile_id]) %>
              <span class="eliminarComentario"> <%= link_to 'Eliminar', c, method: :delete, data: { confirm: '¿Estas seguro que quieres eliminar este comentario?'} %> </span>
            <% end %>

          </div>
          <div class="contenidoComentario">
        			<%= c.comment %>
          </div>
      </div>
		<% end %>
<% end %>
    </div>
 </section>

app/views/books/showadmin.html.erb
<%= render 'header' %>

<%= link_to 'Volver', books_indexadmin_path, class:"nuevoLibro" %>

<div class="libroEnCuestion">
	<img src="<%= @book.picture %>">
	<h2>Título: <%= @book.titulo %></h2>
	<p class="autor"> Autor/es:   	<% @book.authors.each do |a| %>
                									<%= a.autor + "." %>
                									<% end %>
	</p>
	<p class="autor"> Genero Literario:   <%= Genre.find(@book.genre_id).nombre %></p>
	<p class="autor"> Categoria:   <%= Category.find(@book.category_id).nombre %></p>
   	<p class="autor"> Editorial:   <%= @book.editorial %></p>
   	<p class="autor"> Lanzamiento: <%= @book.indate.strftime("%d/%m/%Y") %></p>
   	<p class="autor"> Caducidad:  <%= @book.outdate.strftime("%d/%m/%Y") %> </p>
</div>

<%= link_to 'Editar Libro', edit_book_path(@book), class:"nuevoLibro" %>

<div class="cabecera">
	<p>Capítulos</p>
</div>
<section class="ListadoLibrosAdmin">

		<article class="libro">
			<div class="encabezado">Numero</div>
			<div class="encabezado">Titulo</div>
			<div class="encabezado">PDF</div>
			<div class="encabezado">Lanzamiento</div>
			<div class="encabezado">Caducidad</div>
		</article>

	<% @book.capitulos.each do |b| %>

		<article class="libro">
			<div class="imagen"><%= b.numero %></div>
			<div class="titulo"><%= b.titulo %></div>
			<div class="titulo" style="overflow-x: scroll;"><%= b.pdf %></div>
			<div class="titulo"><%= b.indate.strftime("%d/%m/%Y") %></div>
			<div class="titulo"><%= b.outdate.strftime("%d/%m/%Y") %></div>
			<div class="titulo"><%= link_to 'Editar capitulo', edit_book_capitulo_path(@book.id,b) %></div>
			<div class="titulo"><%= link_to 'Eliminar capitulo', borrar_book_capitulo_path(@book.id,b) , data: { confirm: '¿Estas seguro que deseas eliminar el capitulo?'} %></div>
			
		</article>



	<% end %>
</section>
<%= link_to 'Agregar capítulo', new_book_capitulo_path(@book.id), class:"nuevoLibro" %>

<%= link_to 'Eliminar Libro', @book, method: :delete, data: { confirm: '¿Estas seguro que deseas eliminar el libro?'},class:"eliminarLibro" %>